sudo: true
language: cpp

compiler:
  - gcc

before_install:
  #- sudo apt-get install libwt-dev # conflicts
  #- sudo apt-get install witty-dev # conflicts
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705
  - sudo apt-get update -qq

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost1.55-all-dev
    - libwt-dev

script: 
 - ./build.sh

after_success:
  - codecov